#!/usr/bin/env python3
"""Seed the NOVA LABS database with 6 phases, 30 days of content, and 10 MCQs per day."""
import json
import sqlite3
import uuid
from datetime import datetime, timezone

DB_PATH = "novalabs.db"

PHASES = [
    {"name": "HTML & CSS Foundations", "tagline": "Build the visual web", "color": "#2F67C7", "skills": ["HTML5", "CSS3", "Flexbox", "Grid", "Responsive Design"], "days": "1–5"},
    {"name": "JavaScript Essentials", "tagline": "Make it interactive", "color": "#8A2BBE", "skills": ["Variables", "Functions", "DOM", "Events", "ES6+", "Async/Await"], "days": "6–10"},
    {"name": "React & Frontend", "tagline": "Component-driven UI", "color": "#22C7D4", "skills": ["JSX", "Components", "State", "Props", "Hooks", "React Router"], "days": "11–15"},
    {"name": "Backend & APIs", "tagline": "Server-side power", "color": "#D21D8E", "skills": ["Python", "FastAPI", "REST APIs", "Middleware", "Validation"], "days": "16–20"},
    {"name": "Database & Auth", "tagline": "Store and protect", "color": "#2236A8", "skills": ["SQLite", "SQLAlchemy", "JWT", "Bcrypt", "Sessions", "RBAC"], "days": "21–25"},
    {"name": "Deployment & Projects", "tagline": "Ship it live", "color": "#F02B8F", "skills": ["Docker", "CI/CD", "Vercel", "Testing", "Portfolio"], "days": "26–30"},
]

DAYS = [
    # Phase 1: HTML & CSS
    {"day": 1, "title": "HTML Fundamentals", "time": "45 min", "lang": "html", "type": "code",
     "lesson": """# HTML Fundamentals\n\nHTML (HyperText Markup Language) is the backbone of every web page. It defines the **structure** and **content** of your website.\n\n## Document Structure\n\nEvery HTML page follows this basic structure:\n\n```html\n<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <title>My Page</title>\n</head>\n<body>\n  <h1>Hello, World!</h1>\n</body>\n</html>\n```\n\n## Essential Tags\n\n- **Headings**: `<h1>` through `<h6>` — define content hierarchy\n- **Paragraphs**: `<p>` — for text blocks\n- **Links**: `<a href="url">` — navigation between pages\n- **Images**: `<img src="path" alt="description">` — visual content\n- **Lists**: `<ul>`, `<ol>`, `<li>` — organized information\n- **Divs & Spans**: `<div>` (block) and `<span>` (inline) — for grouping\n\n## Semantic HTML\n\nUse semantic tags like `<header>`, `<nav>`, `<main>`, `<article>`, `<section>`, and `<footer>` to give meaning to your layout. Search engines and screen readers rely on these.""",
     "assignment": "Create a personal profile page using semantic HTML. Include:\n- A `<header>` with your name in an `<h1>`\n- A `<nav>` with 3 links\n- A `<main>` section with an `<article>` about yourself\n- An `<img>` tag (use any placeholder URL)\n- An ordered list of your top 3 skills\n- A `<footer>` with a copyright notice",
     "starter": '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <title>My Profile</title>\n</head>\n<body>\n  <!-- Build your profile page here -->\n  \n</body>\n</html>'},
    {"day": 2, "title": "CSS Styling & Selectors", "time": "50 min", "lang": "html", "type": "code",
     "lesson": """# CSS Styling & Selectors\n\nCSS (Cascading Style Sheets) controls the **visual presentation** of HTML elements.\n\n## Adding CSS\n\nThree ways to add CSS:\n1. **Inline**: `<p style="color: red;">`\n2. **Internal**: `<style>` tag in `<head>`\n3. **External**: `<link rel="stylesheet" href="style.css">` (preferred)\n\n## Selectors\n\n```css\n/* Element selector */\np { color: #333; }\n\n/* Class selector */\n.highlight { background: yellow; }\n\n/* ID selector */\n#main-title { font-size: 2rem; }\n\n/* Descendant selector */\nnav a { text-decoration: none; }\n```\n\n## The Box Model\n\nEvery element is a box with: **content** → **padding** → **border** → **margin**.\n\n```css\n.card {\n  padding: 20px;\n  border: 1px solid #ddd;\n  margin: 16px 0;\n  border-radius: 8px;\n}\n```\n\n## Key Properties\n\n- `color`, `background-color` — colors\n- `font-size`, `font-weight`, `font-family` — typography\n- `width`, `height`, `max-width` — sizing\n- `padding`, `margin` — spacing\n- `border`, `border-radius` — borders""",
     "assignment": "Style the profile page from Day 1. Add CSS to:\n- Set a custom font family and base font size\n- Style the header with a background color and centered text\n- Make links change color on hover\n- Add padding and margin to sections\n- Style the skills list with custom bullet points\n- Add a border and border-radius to a card-like section",
     "starter": '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <title>Styled Profile</title>\n  <style>\n    /* Add your CSS here */\n    body {\n      font-family: sans-serif;\n      margin: 0;\n      padding: 0;\n    }\n  </style>\n</head>\n<body>\n  <header>\n    <h1>Your Name</h1>\n  </header>\n  <main>\n    <section class="about">\n      <h2>About Me</h2>\n      <p>Write something about yourself.</p>\n    </section>\n  </main>\n</body>\n</html>'},
    {"day": 3, "title": "Flexbox Layout", "time": "50 min", "lang": "html", "type": "code",
     "lesson": """# Flexbox Layout\n\nFlexbox is a one-dimensional layout system for arranging items in rows or columns.\n\n## Container Properties\n\n```css\n.container {\n  display: flex;\n  flex-direction: row;      /* row | column */\n  justify-content: center;  /* main axis alignment */\n  align-items: center;      /* cross axis alignment */\n  gap: 16px;                /* space between items */\n  flex-wrap: wrap;          /* allow wrapping */\n}\n```\n\n## Item Properties\n\n```css\n.item {\n  flex: 1;          /* grow to fill space */\n  flex-shrink: 0;   /* don't shrink */\n  order: 2;         /* change visual order */\n  align-self: end;  /* override container alignment */\n}\n```\n\n## Common Patterns\n\n- **Centering**: `display: flex; justify-content: center; align-items: center;`\n- **Navbar**: `display: flex; justify-content: space-between;`\n- **Card grid**: `display: flex; flex-wrap: wrap; gap: 16px;`""",
     "assignment": "Build a responsive navigation bar and a card layout using Flexbox:\n- A sticky navbar with a logo on the left and links on the right\n- A hero section with centered content\n- A 3-column card grid that wraps on smaller screens\n- Each card should have an icon, title, and description",
     "starter": '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>Flexbox Layout</title>\n  <style>\n    * { box-sizing: border-box; margin: 0; padding: 0; }\n    body { font-family: sans-serif; }\n    /* Add your flexbox styles here */\n  </style>\n</head>\n<body>\n  <nav>\n    <!-- Logo and links -->\n  </nav>\n  <main>\n    <!-- Hero and cards -->\n  </main>\n</body>\n</html>'},
    {"day": 4, "title": "CSS Grid & Responsive Design", "time": "55 min", "lang": "html", "type": "code",
     "lesson": """# CSS Grid & Responsive Design\n\n## CSS Grid\n\nGrid is a two-dimensional layout system — rows AND columns.\n\n```css\n.grid {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  grid-template-rows: auto;\n  gap: 20px;\n}\n\n.wide {\n  grid-column: span 2; /* span multiple columns */\n}\n```\n\n## Media Queries\n\nMake layouts responsive:\n\n```css\n/* Mobile first */\n.grid {\n  grid-template-columns: 1fr;\n}\n\n/* Tablet */\n@media (min-width: 768px) {\n  .grid { grid-template-columns: repeat(2, 1fr); }\n}\n\n/* Desktop */\n@media (min-width: 1024px) {\n  .grid { grid-template-columns: repeat(3, 1fr); }\n}\n```\n\n## Mobile-First Approach\n\nAlways design for mobile first, then enhance for larger screens. Use `min-width` media queries to add complexity as screen size grows.""",
     "assignment": "Create a responsive dashboard layout using CSS Grid:\n- A header spanning the full width\n- A sidebar and main content area (sidebar collapses on mobile)\n- A 2x2 grid of stat cards in the main area\n- Responsive: 1 column on mobile, 2 on tablet, full layout on desktop\n- Use `grid-template-areas` for the overall page layout",
     "starter": '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>Grid Dashboard</title>\n  <style>\n    * { box-sizing: border-box; margin: 0; }\n    body { font-family: sans-serif; min-height: 100vh; }\n    /* Build your grid layout here */\n  </style>\n</head>\n<body>\n  <!-- Dashboard layout -->\n</body>\n</html>'},
    {"day": 5, "title": "Forms, Animations & Mini-Project", "time": "60 min", "lang": "html", "type": "code",
     "lesson": """# Forms, Animations & Phase 1 Recap\n\n## HTML Forms\n\n```html\n<form action="/submit" method="POST">\n  <label for="email">Email</label>\n  <input type="email" id="email" name="email" required>\n  \n  <label for="msg">Message</label>\n  <textarea id="msg" name="message"></textarea>\n  \n  <button type="submit">Send</button>\n</form>\n```\n\n## CSS Transitions & Animations\n\n```css\n/* Transitions */\n.btn {\n  transition: all 0.3s ease;\n}\n.btn:hover {\n  transform: translateY(-2px);\n  box-shadow: 0 4px 12px rgba(0,0,0,0.15);\n}\n\n/* Keyframe animations */\n@keyframes fadeIn {\n  from { opacity: 0; transform: translateY(20px); }\n  to { opacity: 1; transform: translateY(0); }\n}\n.card { animation: fadeIn 0.5s ease; }\n```\n\n## CSS Custom Properties\n\n```css\n:root {\n  --primary: #2F67C7;\n  --radius: 8px;\n}\n.btn {\n  background: var(--primary);\n  border-radius: var(--radius);\n}\n```""",
     "assignment": "Build a complete landing page that combines everything from Phase 1:\n- Responsive navbar with a hamburger menu concept\n- Hero section with animated text\n- Features section using CSS Grid\n- A contact form with styled inputs\n- Smooth hover transitions on all interactive elements\n- Use CSS custom properties for theming",
     "starter": '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>Landing Page</title>\n  <style>\n    :root {\n      --primary: #2F67C7;\n      --text: #1B237A;\n      --gray: #6B7280;\n    }\n    * { box-sizing: border-box; margin: 0; padding: 0; }\n    body { font-family: sans-serif; color: var(--text); }\n  </style>\n</head>\n<body>\n  <!-- Build your landing page -->\n</body>\n</html>'},
    # Phase 2: JavaScript
    {"day": 6, "title": "JavaScript Basics — Variables, Types & Operators", "time": "45 min", "lang": "javascript", "type": "code",
     "lesson": "# JavaScript Basics\n\nJavaScript makes web pages interactive.\n\n## Variables\n\n```javascript\nconst name = 'Alice';  // constant - can't reassign\nlet age = 25;          // mutable - can reassign\n// var is legacy — avoid it\n```\n\n## Data Types\n\n- **String**: `'hello'`, `\"world\"`, `` `template ${var}` ``\n- **Number**: `42`, `3.14`\n- **Boolean**: `true`, `false`\n- **Array**: `[1, 2, 3]`\n- **Object**: `{ name: 'Alice', age: 25 }`\n- **null / undefined**\n\n## Operators\n\n```javascript\n// Comparison (always use ===)\n5 === '5'  // false (strict equality)\n5 == '5'   // true (loose — avoid)\n\n// Logical\ntrue && false  // AND\ntrue || false  // OR\n!true          // NOT\n\n// Template literals\nconst greeting = `Hello, ${name}! You are ${age}.`;\n```",
     "assignment": "Write a JavaScript program that:\n1. Declares variables for a user profile (name, age, skills array, isStudent boolean)\n2. Uses template literals to create a formatted bio string\n3. Checks if the user is an adult (age >= 18)\n4. Adds a new skill to the skills array\n5. Logs everything to the console",
     "starter": "// User Profile Program\n\n// 1. Declare your variables here\n\n// 2. Create a bio using template literals\n\n// 3. Check if adult\n\n// 4. Add a skill\n\n// 5. Log results\nconsole.log('Start coding!');"},
    {"day": 7, "title": "Functions & Control Flow", "time": "50 min", "lang": "javascript", "type": "code",
     "lesson": "# Functions & Control Flow\n\n## Functions\n\n```javascript\n// Function declaration\nfunction greet(name) {\n  return `Hello, ${name}!`;\n}\n\n// Arrow function\nconst add = (a, b) => a + b;\n\n// Default parameters\nconst greetUser = (name = 'Guest') => `Hi, ${name}`;\n```\n\n## Control Flow\n\n```javascript\n// if/else\nif (score >= 90) {\n  grade = 'A';\n} else if (score >= 80) {\n  grade = 'B';\n} else {\n  grade = 'C';\n}\n\n// Ternary\nconst status = age >= 18 ? 'adult' : 'minor';\n\n// Switch\nswitch (day) {\n  case 'Mon': console.log('Start of week'); break;\n  case 'Fri': console.log('Almost weekend!'); break;\n  default: console.log('Regular day');\n}\n```\n\n## Loops\n\n```javascript\n// for loop\nfor (let i = 0; i < 5; i++) { console.log(i); }\n\n// for...of (arrays)\nfor (const item of ['a', 'b', 'c']) { console.log(item); }\n\n// while\nlet count = 0;\nwhile (count < 3) { count++; }\n```",
     "assignment": "Build a grade calculator:\n1. Write a function `calculateGrade(score)` that returns a letter grade\n2. Write a function `getGPA(grades)` that takes an array of letter grades and returns a GPA\n3. Write a function `isHonorRoll(gpa)` using a ternary\n4. Test with sample data and log results",
     "starter": "// Grade Calculator\n\nfunction calculateGrade(score) {\n  // Return 'A', 'B', 'C', 'D', or 'F'\n}\n\nfunction getGPA(grades) {\n  // Convert letter grades to numbers and average\n}\n\nfunction isHonorRoll(gpa) {\n  // Return true if GPA >= 3.5\n}\n\n// Test your functions\nconst scores = [92, 85, 78, 95, 88];\nconsole.log('Start coding!');"},
    {"day": 8, "title": "Arrays & Objects — Deep Dive", "time": "55 min", "lang": "javascript", "type": "code",
     "lesson": "# Arrays & Objects\n\n## Array Methods\n\n```javascript\nconst nums = [1, 2, 3, 4, 5];\n\n// Transform\nnums.map(n => n * 2);        // [2, 4, 6, 8, 10]\nnums.filter(n => n > 3);     // [4, 5]\nnums.reduce((sum, n) => sum + n, 0); // 15\n\n// Search\nnums.find(n => n > 3);       // 4\nnums.includes(3);            // true\nnums.indexOf(3);             // 2\n\n// Modify\nnums.push(6);                // add to end\nnums.splice(1, 1);           // remove at index\nconst sorted = [...nums].sort((a, b) => a - b);\n```\n\n## Objects\n\n```javascript\nconst user = {\n  name: 'Alice',\n  age: 25,\n  skills: ['JS', 'React'],\n};\n\n// Destructuring\nconst { name, age } = user;\n\n// Spread\nconst updated = { ...user, age: 26 };\n\n// Object methods\nObject.keys(user);    // ['name', 'age', 'skills']\nObject.values(user);  // ['Alice', 25, [...]]\nObject.entries(user); // [['name', 'Alice'], ...]\n```",
     "assignment": "Build a student management system:\n1. Create an array of 5 student objects (name, grade, scores array)\n2. Use `.map()` to add an `average` property to each student\n3. Use `.filter()` to find honor roll students (avg >= 90)\n4. Use `.reduce()` to find the class average\n5. Use `.sort()` to rank students by average\n6. Use destructuring to log the top student",
     "starter": "// Student Management System\n\nconst students = [\n  // Add 5 students with name, grade, scores\n];\n\n// 1. Calculate averages\n\n// 2. Find honor roll\n\n// 3. Class average\n\n// 4. Rank students\n\n// 5. Log top student\nconsole.log('Start coding!');"},
    {"day": 9, "title": "DOM Manipulation & Events", "time": "55 min", "lang": "javascript", "type": "code",
     "lesson": "# DOM Manipulation & Events\n\nThe DOM (Document Object Model) lets JavaScript interact with HTML.\n\n## Selecting Elements\n\n```javascript\nconst el = document.getElementById('myId');\nconst el2 = document.querySelector('.myClass');\nconst all = document.querySelectorAll('p');\n```\n\n## Modifying Elements\n\n```javascript\nel.textContent = 'New text';\nel.innerHTML = '<strong>Bold</strong>';\nel.style.color = 'blue';\nel.classList.add('active');\nel.classList.toggle('hidden');\nel.setAttribute('data-id', '42');\n```\n\n## Creating Elements\n\n```javascript\nconst div = document.createElement('div');\ndiv.textContent = 'Hello';\ndiv.className = 'card';\ndocument.body.appendChild(div);\n```\n\n## Event Handling\n\n```javascript\nbutton.addEventListener('click', (e) => {\n  console.log('Clicked!', e.target);\n});\n\ninput.addEventListener('input', (e) => {\n  console.log(e.target.value);\n});\n\nform.addEventListener('submit', (e) => {\n  e.preventDefault();\n  // handle form data\n});\n```",
     "assignment": "Build an interactive to-do list:\n1. A form with an input and 'Add' button\n2. Adding a task creates a new list item dynamically\n3. Each task has a 'Complete' button (toggles strikethrough) and 'Delete' button\n4. Show a task counter that updates in real-time\n5. Store tasks in an array and re-render on changes",
     "starter": "// To-Do List App\n// Note: In the browser, you'd have HTML. Here, simulate with console.\n\nconst tasks = [];\n\nfunction addTask(text) {\n  // Add task to array\n}\n\nfunction toggleTask(index) {\n  // Toggle completed status\n}\n\nfunction deleteTask(index) {\n  // Remove task\n}\n\nfunction renderTasks() {\n  // Display all tasks\n  console.log('Tasks:', tasks);\n}\n\n// Test\naddTask('Learn JavaScript');\naddTask('Build a project');\nrenderTasks();"},
    {"day": 10, "title": "Async JavaScript — Promises, Fetch & APIs", "time": "60 min", "lang": "javascript", "type": "code",
     "lesson": "# Async JavaScript\n\n## Promises\n\n```javascript\nconst fetchData = () => {\n  return new Promise((resolve, reject) => {\n    setTimeout(() => resolve('Data loaded'), 1000);\n  });\n};\n\nfetchData().then(data => console.log(data)).catch(err => console.error(err));\n```\n\n## Async/Await\n\n```javascript\nasync function loadUser() {\n  try {\n    const response = await fetch('https://api.example.com/user');\n    const data = await response.json();\n    return data;\n  } catch (error) {\n    console.error('Failed:', error);\n  }\n}\n```\n\n## Fetch API\n\n```javascript\n// GET request\nconst res = await fetch('/api/users');\nconst users = await res.json();\n\n// POST request\nconst res2 = await fetch('/api/users', {\n  method: 'POST',\n  headers: { 'Content-Type': 'application/json' },\n  body: JSON.stringify({ name: 'Alice' }),\n});\n```\n\n## Error Handling\n\nAlways wrap async calls in try/catch. Check `response.ok` before parsing.",
     "assignment": "Build an API data fetcher:\n1. Write an async function that fetches data from a public API\n2. Parse the JSON response\n3. Handle errors gracefully with try/catch\n4. Implement a simple retry mechanism (retry up to 3 times on failure)\n5. Log the results in a formatted way",
     "starter": "// API Data Fetcher\n\nasync function fetchWithRetry(url, retries = 3) {\n  // Implement retry logic\n}\n\nasync function main() {\n  // Fetch and display data\n  console.log('Fetching data...');\n}\n\nmain();"},
    # Phase 3: React
    {"day": 11, "title": "React Fundamentals — JSX & Components", "time": "50 min", "lang": "javascript", "type": "code",
     "lesson": "# React Fundamentals\n\nReact is a library for building user interfaces with **components**.\n\n## JSX\n\nJSX lets you write HTML-like syntax in JavaScript:\n\n```jsx\nconst element = <h1 className=\"title\">Hello, React!</h1>;\n\n// Expressions in JSX\nconst name = 'Alice';\nconst greeting = <p>Welcome, {name}!</p>;\n```\n\n## Components\n\n```jsx\n// Function component\nfunction Welcome({ name }) {\n  return <h1>Hello, {name}</h1>;\n}\n\n// Usage\n<Welcome name=\"Alice\" />\n```\n\n## Props\n\nProps are read-only inputs to components:\n\n```jsx\nfunction Card({ title, description, children }) {\n  return (\n    <div className=\"card\">\n      <h2>{title}</h2>\n      <p>{description}</p>\n      {children}\n    </div>\n  );\n}\n```\n\n## Conditional Rendering\n\n```jsx\n{isLoggedIn ? <Dashboard /> : <Login />}\n{items.length > 0 && <ItemList items={items} />}\n```",
     "assignment": "Create a React component hierarchy:\n1. A `UserCard` component that takes name, role, and avatar props\n2. A `UserList` component that renders multiple `UserCard`s\n3. A `SearchBar` component (UI only for now)\n4. An `App` component that composes them all\n5. Use conditional rendering to show 'No users found' when the list is empty",
     "starter": "// React Components (conceptual - write the component code)\n\n// UserCard component\nfunction UserCard({ name, role, avatar }) {\n  // Return JSX\n}\n\n// UserList component\nfunction UserList({ users }) {\n  // Map over users and render UserCards\n}\n\n// App component\nfunction App() {\n  const users = [\n    { name: 'Alice', role: 'Developer', avatar: 'A' },\n    { name: 'Bob', role: 'Designer', avatar: 'B' },\n  ];\n  // Compose components\n}\n\nconsole.log('Write your React components above');"},
    {"day": 12, "title": "State Management with useState", "time": "50 min", "lang": "javascript", "type": "code",
     "lesson": "# State Management with useState\n\n`useState` lets components hold and update data.\n\n```jsx\nimport { useState } from 'react';\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n  \n  return (\n    <div>\n      <p>Count: {count}</p>\n      <button onClick={() => setCount(count + 1)}>+</button>\n      <button onClick={() => setCount(prev => prev - 1)}>-</button>\n    </div>\n  );\n}\n```\n\n## Rules\n\n1. Only call hooks at the top level\n2. Only call hooks in React functions\n3. Use the **functional updater** when new state depends on old: `setCount(prev => prev + 1)`\n\n## Complex State\n\n```jsx\nconst [form, setForm] = useState({ name: '', email: '' });\n\n// Update one field\nsetForm(prev => ({ ...prev, name: 'Alice' }));\n```\n\n## State vs Props\n\n- **Props**: passed from parent, read-only\n- **State**: owned by component, mutable via setter",
     "assignment": "Build a counter app with these features:\n1. Increment, decrement, and reset buttons\n2. A step size input (increment/decrement by custom amount)\n3. A history array that tracks all changes\n4. An undo button that reverts the last change\n5. Display min and max values reached",
     "starter": "// Counter with History\nimport { useState } from 'react';\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n  const [step, setStep] = useState(1);\n  const [history, setHistory] = useState([0]);\n  \n  // Implement increment, decrement, reset, undo\n  \n  return null; // Build your JSX\n}\n\nconsole.log('Build the Counter component');"},
    {"day": 13, "title": "useEffect, Lifecycle & Data Fetching", "time": "55 min", "lang": "javascript", "type": "code",
     "lesson": "# useEffect & Data Fetching\n\n`useEffect` runs side effects in components.\n\n```jsx\nimport { useState, useEffect } from 'react';\n\nfunction UserProfile({ userId }) {\n  const [user, setUser] = useState(null);\n  const [loading, setLoading] = useState(true);\n  \n  useEffect(() => {\n    const fetchUser = async () => {\n      setLoading(true);\n      const res = await fetch(`/api/users/${userId}`);\n      const data = await res.json();\n      setUser(data);\n      setLoading(false);\n    };\n    fetchUser();\n  }, [userId]); // Re-run when userId changes\n  \n  if (loading) return <p>Loading...</p>;\n  return <h1>{user.name}</h1>;\n}\n```\n\n## Cleanup\n\n```jsx\nuseEffect(() => {\n  const timer = setInterval(() => console.log('tick'), 1000);\n  return () => clearInterval(timer); // cleanup\n}, []);\n```\n\n## Dependency Array\n\n- `[]` — run once on mount\n- `[dep]` — run when `dep` changes\n- No array — run every render (avoid)",
     "assignment": "Build a data dashboard component:\n1. Fetch a list of items from a mock API on mount\n2. Show a loading spinner while fetching\n3. Display items in a list\n4. Add a refresh button that re-fetches\n5. Add a search filter that filters items client-side\n6. Handle errors with a retry button",
     "starter": "// Data Dashboard\nimport { useState, useEffect } from 'react';\n\nfunction Dashboard() {\n  const [items, setItems] = useState([]);\n  const [loading, setLoading] = useState(true);\n  const [error, setError] = useState(null);\n  const [search, setSearch] = useState('');\n  \n  // Implement data fetching with useEffect\n  \n  return null; // Build your JSX\n}\n\nconsole.log('Build the Dashboard component');"},
    {"day": 14, "title": "React Router & Multi-Page Apps", "time": "50 min", "lang": "javascript", "type": "code",
     "lesson": "# React Router\n\nReact Router enables client-side navigation.\n\n## Setup (Next.js App Router)\n\nIn Next.js 14, routing is file-based:\n\n```\napp/\n  page.tsx          → /\n  about/page.tsx    → /about\n  blog/[id]/page.tsx → /blog/123\n  (auth)/login/page.tsx → /login (grouped)\n```\n\n## Navigation\n\n```jsx\nimport Link from 'next/link';\nimport { useRouter } from 'next/navigation';\n\n// Declarative\n<Link href=\"/about\">About</Link>\n\n// Programmatic\nconst router = useRouter();\nrouter.push('/dashboard');\n```\n\n## Dynamic Routes\n\n```jsx\n// app/blog/[id]/page.tsx\nexport default function BlogPost({ params }) {\n  const { id } = params;\n  return <h1>Post {id}</h1>;\n}\n```\n\n## Layouts\n\nShared UI across routes:\n\n```jsx\n// app/dashboard/layout.tsx\nexport default function DashboardLayout({ children }) {\n  return (\n    <div className=\"flex\">\n      <Sidebar />\n      <main>{children}</main>\n    </div>\n  );\n}\n```",
     "assignment": "Design a multi-page app structure:\n1. Plan the route structure for a blog platform\n2. Create a layout component with navbar and sidebar\n3. Implement a dynamic blog post page that reads the ID from the URL\n4. Add active link highlighting in the navbar\n5. Create a 404 not-found page",
     "starter": "// Multi-Page App Structure\n// Design your route structure and components\n\n// Layout component\nfunction Layout({ children }) {\n  return null; // navbar + sidebar + children\n}\n\n// Blog post page\nfunction BlogPost({ id }) {\n  return null; // Fetch and display post by ID\n}\n\n// Not found page\nfunction NotFound() {\n  return null; // 404 page\n}\n\nconsole.log('Design your multi-page app');"},
    {"day": 15, "title": "Project: Task Manager App", "time": "90 min", "lang": "javascript", "type": "project",
     "lesson": "# Project: Task Manager App\n\nTime to combine everything from Phase 3! Build a full Task Manager with React.\n\n## Requirements\n\n1. **Task CRUD**: Create, read, update, delete tasks\n2. **Categories**: Organize tasks by category (Work, Personal, Study)\n3. **Priorities**: High, Medium, Low with visual indicators\n4. **Filters**: Filter by category, priority, completion status\n5. **Persistence**: Save to localStorage\n6. **Responsive**: Works on mobile and desktop\n\n## Architecture\n\n```\nApp\n├── Header (title + add button)\n├── FilterBar (category, priority, status filters)\n├── TaskList\n│   └── TaskItem (checkbox, title, category badge, delete)\n└── AddTaskModal (form with title, category, priority)\n```\n\n## Tips\n\n- Use `useState` for tasks array and filter state\n- Use `useEffect` to sync with localStorage\n- Extract reusable components (Badge, Modal, Select)\n- Keep state as high as needed, but no higher",
     "assignment": "Build the Task Manager:\n- Add task form with title, category, priority\n- Display tasks in a list with completion toggle\n- Filter tasks by category and priority\n- Delete tasks with confirmation\n- Persist to localStorage\n- Track completion statistics",
     "starter": "// Task Manager App\nimport { useState, useEffect } from 'react';\n\nfunction TaskManager() {\n  const [tasks, setTasks] = useState([]);\n  const [filter, setFilter] = useState({ category: 'all', priority: 'all' });\n  \n  // Load from localStorage on mount\n  useEffect(() => {\n    const saved = localStorage.getItem('tasks');\n    if (saved) setTasks(JSON.parse(saved));\n  }, []);\n  \n  // Save to localStorage on change\n  useEffect(() => {\n    localStorage.setItem('tasks', JSON.stringify(tasks));\n  }, [tasks]);\n  \n  // Implement CRUD operations\n  \n  return null; // Build your JSX\n}\n\nconsole.log('Build the Task Manager');"},
    # Phase 4: Backend
    {"day": 16, "title": "Python Fundamentals for Backend", "time": "50 min", "lang": "python", "type": "code",
     "lesson": "# Python for Backend Development\n\n## Why Python?\n\nPython is perfect for backend development: clean syntax, rich ecosystem, and powerful frameworks.\n\n## Data Types & Structures\n\n```python\n# Variables\nname: str = 'Alice'\nage: int = 25\nis_active: bool = True\n\n# Lists\nskills = ['Python', 'FastAPI', 'SQL']\nskills.append('Docker')\n\n# Dictionaries\nuser = {'name': 'Alice', 'age': 25}\nuser['email'] = 'alice@example.com'\n\n# List comprehensions\nsquares = [x**2 for x in range(10)]\nevens = [x for x in range(20) if x % 2 == 0]\n```\n\n## Functions\n\n```python\ndef greet(name: str, greeting: str = 'Hello') -> str:\n    return f'{greeting}, {name}!'\n\n# Lambda\nsort_by_age = lambda user: user['age']\n```\n\n## Error Handling\n\n```python\ntry:\n    result = int('abc')\nexcept ValueError as e:\n    print(f'Error: {e}')\nfinally:\n    print('Done')\n```",
     "assignment": "Write Python functions for a user management system:\n1. `create_user(name, email, age)` — returns a user dict with an auto-generated ID\n2. `validate_email(email)` — checks if email format is valid\n3. `filter_users(users, min_age)` — filter users above a minimum age\n4. `sort_users(users, key)` — sort by any field\n5. `user_stats(users)` — return count, average age, most common domain",
     "starter": "# User Management System\nimport uuid\n\ndef create_user(name: str, email: str, age: int) -> dict:\n    pass\n\ndef validate_email(email: str) -> bool:\n    pass\n\ndef filter_users(users: list, min_age: int) -> list:\n    pass\n\ndef sort_users(users: list, key: str) -> list:\n    pass\n\ndef user_stats(users: list) -> dict:\n    pass\n\n# Test your functions\nprint('Start coding!')"},
    {"day": 17, "title": "FastAPI — Your First API", "time": "55 min", "lang": "python", "type": "code",
     "lesson": "# FastAPI — Building APIs\n\nFastAPI is a modern Python web framework for building APIs.\n\n## Hello World\n\n```python\nfrom fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get('/')\ndef root():\n    return {'message': 'Hello, World!'}\n\n@app.get('/users/{user_id}')\ndef get_user(user_id: int):\n    return {'user_id': user_id}\n```\n\n## Request Body\n\n```python\nfrom pydantic import BaseModel\n\nclass UserCreate(BaseModel):\n    name: str\n    email: str\n    age: int\n\n@app.post('/users')\ndef create_user(user: UserCreate):\n    return {'id': 1, **user.model_dump()}\n```\n\n## Query Parameters\n\n```python\n@app.get('/users')\ndef list_users(skip: int = 0, limit: int = 10):\n    return users[skip:skip + limit]\n```\n\n## Response Models\n\n```python\nclass UserResponse(BaseModel):\n    id: int\n    name: str\n\n@app.get('/users/{id}', response_model=UserResponse)\ndef get_user(id: int):\n    return find_user(id)\n```",
     "assignment": "Build a REST API for a bookstore:\n1. `GET /books` — list all books with optional search query\n2. `POST /books` — add a new book (title, author, price, isbn)\n3. `GET /books/{id}` — get a specific book\n4. `PUT /books/{id}` — update a book\n5. `DELETE /books/{id}` — delete a book\nUse Pydantic models for request/response validation.",
     "starter": "from fastapi import FastAPI, HTTPException\nfrom pydantic import BaseModel\n\napp = FastAPI()\n\n# In-memory storage\nbooks = []\n\nclass BookCreate(BaseModel):\n    title: str\n    author: str\n    price: float\n    isbn: str\n\n# Implement your endpoints\n\nprint('Build your bookstore API!')"},
    {"day": 18, "title": "Middleware, CORS & Error Handling", "time": "50 min", "lang": "python", "type": "code",
     "lesson": "# Middleware & Error Handling\n\n## Middleware\n\n```python\nfrom fastapi import FastAPI, Request\nimport time\n\n@app.middleware('http')\nasync def add_timing(request: Request, call_next):\n    start = time.time()\n    response = await call_next(request)\n    duration = time.time() - start\n    response.headers['X-Process-Time'] = str(duration)\n    return response\n```\n\n## CORS\n\n```python\nfrom fastapi.middleware.cors import CORSMiddleware\n\napp.add_middleware(\n    CORSMiddleware,\n    allow_origins=['http://localhost:3000'],\n    allow_credentials=True,\n    allow_methods=['*'],\n    allow_headers=['*'],\n)\n```\n\n## Error Handling\n\n```python\nfrom fastapi import HTTPException\n\n@app.get('/users/{id}')\ndef get_user(id: int):\n    user = db.find(id)\n    if not user:\n        raise HTTPException(status_code=404, detail='User not found')\n    return user\n```\n\n## Dependency Injection\n\n```python\nfrom fastapi import Depends\n\ndef get_db():\n    db = Database()\n    try:\n        yield db\n    finally:\n        db.close()\n\n@app.get('/users')\ndef list_users(db = Depends(get_db)):\n    return db.get_all_users()\n```",
     "assignment": "Enhance the bookstore API with:\n1. A logging middleware that logs every request method and path\n2. CORS configuration for a frontend at localhost:3000\n3. Custom exception handlers for validation errors\n4. A dependency for pagination (skip, limit parameters)\n5. Rate limiting middleware (max 100 requests per minute per IP)",
     "starter": "from fastapi import FastAPI, Request, Depends, HTTPException\nfrom fastapi.middleware.cors import CORSMiddleware\nimport time\n\napp = FastAPI()\n\n# Add your middleware and dependencies\n\nprint('Enhance your API!')"},
    {"day": 19, "title": "File Upload & External APIs", "time": "55 min", "lang": "python", "type": "code",
     "lesson": "# File Upload & External APIs\n\n## File Upload\n\n```python\nfrom fastapi import UploadFile, File\n\n@app.post('/upload')\nasync def upload_file(file: UploadFile = File(...)):\n    contents = await file.read()\n    # Process file\n    return {\n        'filename': file.filename,\n        'size': len(contents),\n        'content_type': file.content_type,\n    }\n```\n\n## Calling External APIs\n\n```python\nimport httpx\n\nasync def fetch_github_user(username: str):\n    async with httpx.AsyncClient() as client:\n        response = await client.get(f'https://api.github.com/users/{username}')\n        response.raise_for_status()\n        return response.json()\n```\n\n## Background Tasks\n\n```python\nfrom fastapi import BackgroundTasks\n\ndef send_email(email: str, message: str):\n    # Simulate sending email\n    time.sleep(2)\n    print(f'Email sent to {email}')\n\n@app.post('/notify')\nasync def notify(email: str, background_tasks: BackgroundTasks):\n    background_tasks.add_task(send_email, email, 'Hello!')\n    return {'message': 'Notification queued'}\n```",
     "assignment": "Build an API that:\n1. Accepts image uploads (validate file type and size)\n2. Fetches user data from GitHub's public API\n3. Combines the data into a profile response\n4. Sends a welcome email as a background task\n5. Returns appropriate error responses for invalid inputs",
     "starter": "from fastapi import FastAPI, UploadFile, File, BackgroundTasks, HTTPException\n\napp = FastAPI()\n\n# Implement your endpoints\n\nprint('Build the profile API!')"},
    {"day": 20, "title": "Project: Notes API", "time": "90 min", "lang": "python", "type": "project",
     "lesson": "# Project: Notes API\n\nBuild a complete RESTful API for a notes application.\n\n## Requirements\n\n1. **CRUD operations** for notes (title, content, tags, created_at)\n2. **Search** by title or content\n3. **Filter** by tags\n4. **Pagination** with cursor-based approach\n5. **Validation** with Pydantic models\n6. **Error handling** with custom exceptions\n\n## Data Model\n\n```python\nclass Note(BaseModel):\n    id: str\n    title: str\n    content: str\n    tags: list[str] = []\n    is_pinned: bool = False\n    created_at: datetime\n    updated_at: datetime\n```\n\n## Endpoints\n\n- `GET /notes` — list with search, filter, pagination\n- `POST /notes` — create\n- `GET /notes/{id}` — read\n- `PUT /notes/{id}` — update\n- `DELETE /notes/{id}` — soft delete\n- `POST /notes/{id}/pin` — toggle pin",
     "assignment": "Build the full Notes API with all endpoints listed above. Include:\n- Pydantic models for request/response\n- In-memory storage (list of dicts)\n- Search across title and content\n- Tag-based filtering\n- Pagination with next_cursor\n- Soft delete (mark as deleted, don't remove)",
     "starter": "from fastapi import FastAPI, HTTPException, Query\nfrom pydantic import BaseModel\nfrom datetime import datetime\nimport uuid\n\napp = FastAPI(title='Notes API')\n\n# Models and storage\nnotes_db = []\n\nclass NoteCreate(BaseModel):\n    title: str\n    content: str\n    tags: list[str] = []\n\n# Implement all endpoints\n\nprint('Build the Notes API!')"},
    # Phase 5: Database & Auth
    {"day": 21, "title": "SQL & SQLAlchemy Basics", "time": "55 min", "lang": "python", "type": "code",
     "lesson": "# SQL & SQLAlchemy\n\n## SQLAlchemy ORM\n\nSQLAlchemy maps Python classes to database tables.\n\n```python\nfrom sqlalchemy import create_engine, Column, Integer, String\nfrom sqlalchemy.orm import DeclarativeBase, Session\n\nclass Base(DeclarativeBase):\n    pass\n\nclass User(Base):\n    __tablename__ = 'users'\n    id = Column(Integer, primary_key=True)\n    name = Column(String(100), nullable=False)\n    email = Column(String(255), unique=True)\n```\n\n## CRUD Operations\n\n```python\n# Create\nuser = User(name='Alice', email='alice@example.com')\nsession.add(user)\nsession.commit()\n\n# Read\nuser = session.query(User).filter(User.email == 'alice@example.com').first()\nall_users = session.query(User).all()\n\n# Update\nuser.name = 'Alice Smith'\nsession.commit()\n\n# Delete\nsession.delete(user)\nsession.commit()\n```\n\n## Async SQLAlchemy\n\n```python\nfrom sqlalchemy.ext.asyncio import create_async_engine, AsyncSession\n\nengine = create_async_engine('sqlite+aiosqlite:///./app.db')\n\nasync with AsyncSession(engine) as session:\n    result = await session.execute(select(User))\n    users = result.scalars().all()\n```",
     "assignment": "Create a database-backed user management system:\n1. Define User and Post models with a relationship\n2. Write functions for CRUD operations on both\n3. Implement a search function that queries by name or email\n4. Add pagination support\n5. Write a function that returns user stats (post count, join date)",
     "starter": "# Database Models\nfrom sqlalchemy import create_engine, Column, Integer, String, ForeignKey, DateTime\nfrom sqlalchemy.orm import DeclarativeBase, relationship, Session\nfrom datetime import datetime\n\nclass Base(DeclarativeBase):\n    pass\n\n# Define your models\n\n# Implement CRUD functions\n\nprint('Build the database layer!')"},
    {"day": 22, "title": "Relationships, Migrations & Queries", "time": "55 min", "lang": "python", "type": "code",
     "lesson": "# Advanced SQLAlchemy\n\n## Relationships\n\n```python\nclass User(Base):\n    __tablename__ = 'users'\n    id = Column(Integer, primary_key=True)\n    posts = relationship('Post', back_populates='author')\n\nclass Post(Base):\n    __tablename__ = 'posts'\n    id = Column(Integer, primary_key=True)\n    author_id = Column(Integer, ForeignKey('users.id'))\n    author = relationship('User', back_populates='posts')\n```\n\n## Advanced Queries\n\n```python\nfrom sqlalchemy import select, func\n\n# Join\nstmt = select(User, func.count(Post.id)).join(Post).group_by(User.id)\n\n# Subquery\ntop_users = select(User).where(\n    User.id.in_(\n        select(Post.author_id).group_by(Post.author_id).having(func.count() > 5)\n    )\n)\n\n# Aggregation\nstats = session.execute(\n    select(func.count(User.id), func.avg(User.age))\n).first()\n```\n\n## Indexes\n\n```python\nclass User(Base):\n    email = Column(String, unique=True, index=True)\n```",
     "assignment": "Build a blog database with:\n1. User, Post, Comment, and Tag models with proper relationships\n2. Many-to-many relationship between Posts and Tags\n3. Query: get all posts by a user with comment count\n4. Query: get top 5 most-used tags\n5. Query: get users who posted in the last 7 days",
     "starter": "# Blog Database\nfrom sqlalchemy import *\nfrom sqlalchemy.orm import DeclarativeBase, relationship, Session\nfrom datetime import datetime, timedelta\n\nclass Base(DeclarativeBase):\n    pass\n\n# Define models with relationships\n\n# Implement queries\n\nprint('Build the blog database!')"},
    {"day": 23, "title": "Authentication — JWT & Password Hashing", "time": "60 min", "lang": "python", "type": "code",
     "lesson": "# Authentication\n\n## Password Hashing\n\nNever store plain passwords. Use bcrypt:\n\n```python\nimport bcrypt\n\ndef hash_password(password: str) -> str:\n    return bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()\n\ndef verify_password(plain: str, hashed: str) -> bool:\n    return bcrypt.checkpw(plain.encode(), hashed.encode())\n```\n\n## JWT Tokens\n\n```python\nfrom jose import jwt\nfrom datetime import datetime, timedelta\n\nSECRET = 'your-secret-key'\nALGORITHM = 'HS256'\n\ndef create_token(user_id: str) -> str:\n    payload = {\n        'sub': user_id,\n        'exp': datetime.utcnow() + timedelta(minutes=15),\n        'type': 'access',\n    }\n    return jwt.encode(payload, SECRET, algorithm=ALGORITHM)\n\ndef verify_token(token: str) -> dict:\n    return jwt.decode(token, SECRET, algorithms=[ALGORITHM])\n```\n\n## Protected Routes\n\n```python\nfrom fastapi import Depends, HTTPException\nfrom fastapi.security import HTTPBearer\n\nsecurity = HTTPBearer()\n\nasync def get_current_user(credentials = Depends(security)):\n    payload = verify_token(credentials.credentials)\n    if not payload:\n        raise HTTPException(status_code=401)\n    return await get_user(payload['sub'])\n\n@app.get('/me')\nasync def profile(user = Depends(get_current_user)):\n    return user\n```",
     "assignment": "Implement a complete auth system:\n1. Signup endpoint with password hashing\n2. Login endpoint that returns JWT access token\n3. A protected /me endpoint\n4. Token refresh logic\n5. Password validation (min 8 chars, must include number)",
     "starter": "from fastapi import FastAPI, HTTPException, Depends\nfrom pydantic import BaseModel\nimport bcrypt\n\napp = FastAPI()\n\n# In-memory user store\nusers = []\n\nclass SignupRequest(BaseModel):\n    email: str\n    password: str\n    name: str\n\n# Implement auth endpoints\n\nprint('Build the auth system!')"},
    {"day": 24, "title": "Authorization, RBAC & Security", "time": "55 min", "lang": "python", "type": "code",
     "lesson": "# Authorization & Security\n\n## Role-Based Access Control\n\n```python\nfrom enum import Enum\n\nclass Role(str, Enum):\n    LEARNER = 'learner'\n    MENTOR = 'mentor'\n    ADMIN = 'admin'\n\ndef require_role(*roles: Role):\n    def dependency(user = Depends(get_current_user)):\n        if user.role not in roles:\n            raise HTTPException(status_code=403, detail='Forbidden')\n        return user\n    return dependency\n\n@app.delete('/users/{id}')\nasync def delete_user(id: str, admin = Depends(require_role(Role.ADMIN))):\n    # Only admins can delete users\n    pass\n```\n\n## Security Best Practices\n\n1. **Never** store secrets in code — use environment variables\n2. **Always** hash passwords with bcrypt (cost factor ≥ 12)\n3. **Validate** all inputs with Pydantic\n4. **Use HTTPS** in production\n5. **Set** httpOnly, Secure flags on cookies\n6. **Rate limit** sensitive endpoints\n7. **Sanitize** user input to prevent injection",
     "assignment": "Build a role-based access system:\n1. Define User model with roles (learner, mentor, admin)\n2. Create a `require_role` dependency\n3. Admin-only endpoint to list all users\n4. Mentor-only endpoint to review submissions\n5. Learner endpoint to view own profile only\n6. Test with different user roles",
     "starter": "from fastapi import FastAPI, Depends, HTTPException\nfrom enum import Enum\n\napp = FastAPI()\n\nclass Role(str, Enum):\n    LEARNER = 'learner'\n    MENTOR = 'mentor'\n    ADMIN = 'admin'\n\n# Implement RBAC\n\nprint('Build the authorization system!')"},
    {"day": 25, "title": "Project: SaaS Dashboard API", "time": "90 min", "lang": "python", "type": "project",
     "lesson": "# Project: SaaS Dashboard API\n\nBuild a complete backend for a SaaS dashboard.\n\n## Features\n\n1. **Auth**: Signup, login, JWT tokens\n2. **Users**: CRUD with roles (admin, member)\n3. **Projects**: Create, list, update projects (scoped to organization)\n4. **Tasks**: CRUD within projects with assignees\n5. **Analytics**: Dashboard stats (task counts, completion rates)\n\n## Data Models\n\n- User (id, name, email, role, org_id)\n- Organization (id, name, plan)\n- Project (id, name, org_id, created_by)\n- Task (id, title, status, priority, assignee_id, project_id)\n\n## Endpoints\n\n- Auth: signup, login, me\n- Projects: CRUD (organization-scoped)\n- Tasks: CRUD (project-scoped)\n- Analytics: GET /dashboard/stats",
     "assignment": "Build the SaaS Dashboard API with all models and endpoints. Focus on:\n- Proper auth with JWT\n- Organization-scoped data access\n- Task assignment and status tracking\n- Dashboard analytics endpoint\n- Clean error handling",
     "starter": "from fastapi import FastAPI\nfrom pydantic import BaseModel\n\napp = FastAPI(title='SaaS Dashboard API')\n\n# Build models, auth, and endpoints\n\nprint('Build the SaaS Dashboard!')"},
    # Phase 6: Deployment
    {"day": 26, "title": "Testing with Pytest & Vitest", "time": "55 min", "lang": "python", "type": "code",
     "lesson": "# Testing\n\n## Python Testing with Pytest\n\n```python\n# test_users.py\nimport pytest\nfrom app import create_user, get_user\n\ndef test_create_user():\n    user = create_user('Alice', 'alice@example.com')\n    assert user['name'] == 'Alice'\n    assert 'id' in user\n\ndef test_create_duplicate_raises():\n    create_user('Alice', 'alice@example.com')\n    with pytest.raises(ValueError):\n        create_user('Alice2', 'alice@example.com')\n\n@pytest.fixture\ndef sample_user():\n    return create_user('Test', 'test@example.com')\n\ndef test_get_user(sample_user):\n    found = get_user(sample_user['id'])\n    assert found['email'] == 'test@example.com'\n```\n\n## FastAPI Testing\n\n```python\nfrom fastapi.testclient import TestClient\nfrom app import app\n\nclient = TestClient(app)\n\ndef test_health():\n    res = client.get('/health')\n    assert res.status_code == 200\n```\n\n## Frontend Testing with Vitest\n\n```javascript\nimport { describe, it, expect } from 'vitest';\nimport { render, screen } from '@testing-library/react';\n\ndescribe('Button', () => {\n  it('renders with text', () => {\n    render(<Button>Click me</Button>);\n    expect(screen.getByText('Click me')).toBeInTheDocument();\n  });\n});\n```",
     "assignment": "Write tests for a user management module:\n1. Test user creation (success and duplicate email)\n2. Test user retrieval (found and not found)\n3. Test user update\n4. Test user deletion\n5. Use fixtures for test data setup\n6. Test edge cases (empty name, invalid email)",
     "starter": "import pytest\n\n# Mock user module\nusers_db = []\n\ndef create_user(name, email):\n    if any(u['email'] == email for u in users_db):\n        raise ValueError('Email exists')\n    user = {'id': len(users_db) + 1, 'name': name, 'email': email}\n    users_db.append(user)\n    return user\n\n# Write your tests\ndef test_create_user():\n    pass\n\nprint('Write your tests!')"},
    {"day": 27, "title": "Docker & Containerization", "time": "50 min", "lang": "html", "type": "code",
     "lesson": "# Docker & Containerization\n\n## Why Docker?\n\nDocker packages your app with all its dependencies into a container that runs anywhere.\n\n## Dockerfile\n\n```dockerfile\n# Python backend\nFROM python:3.11-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nEXPOSE 8000\nCMD [\"uvicorn\", \"app.main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]\n```\n\n## Docker Compose\n\n```yaml\nversion: '3.8'\nservices:\n  backend:\n    build: ./backend\n    ports:\n      - '8000:8000'\n    environment:\n      - DATABASE_URL=sqlite:///./data/app.db\n    volumes:\n      - ./data:/app/data\n  \n  frontend:\n    build: ./frontend\n    ports:\n      - '3000:3000'\n    depends_on:\n      - backend\n```\n\n## Key Commands\n\n```bash\ndocker build -t myapp .          # Build image\ndocker run -p 8000:8000 myapp    # Run container\ndocker compose up -d             # Start all services\ndocker compose down              # Stop all\n```",
     "assignment": "Write Docker configuration for a full-stack app:\n1. Dockerfile for the Python backend\n2. Dockerfile for the Next.js frontend\n3. docker-compose.yml that runs both services\n4. Add health checks to both services\n5. Use multi-stage builds for smaller images",
     "starter": "# Write your Dockerfiles and docker-compose.yml\n# Use comments to explain each line\n\n# --- Backend Dockerfile ---\n# FROM python:3.11-slim\n# ...\n\n# --- Frontend Dockerfile ---\n# FROM node:20-alpine\n# ...\n\n# --- docker-compose.yml ---\n# version: '3.8'\n# services:\n# ...\n\nconsole.log('Write your Docker config!');"},
    {"day": 28, "title": "Project: Open Build — Full-Stack App", "time": "120 min", "lang": "html", "type": "project",
     "lesson": "# Open Build: Full-Stack App\n\nThis is your capstone project. Build a complete full-stack application of your choice.\n\n## Project Ideas\n\n1. **Expense Tracker**: Track income/expenses with charts\n2. **URL Shortener**: Create and track short links\n3. **Chat App**: Real-time messaging with rooms\n4. **Recipe Book**: Save and share recipes\n5. **Habit Tracker**: Track daily habits with streaks\n\n## Requirements (all projects)\n\n- Frontend: React/Next.js with responsive design\n- Backend: FastAPI with proper API structure\n- Database: SQLite with SQLAlchemy\n- Auth: JWT-based authentication\n- Deployment: Dockerized and deployable\n\n## Evaluation Rubric\n\n1. **Functionality** (30pts): Does it work?\n2. **Code Quality** (25pts): Clean, readable, well-structured\n3. **UI/UX** (20pts): Looks good, responsive, accessible\n4. **API Design** (15pts): RESTful, proper status codes\n5. **Deployment** (10pts): Dockerized with README",
     "assignment": "Build your full-stack application:\n1. Choose a project idea (or propose your own)\n2. Set up the project structure\n3. Build the backend API\n4. Build the frontend UI\n5. Connect frontend to backend\n6. Deploy with Docker\n\nSubmit your GitHub repo URL and live deployment URL.",
     "starter": "<!-- Open Build Project -->\n<!-- Choose your project and start building! -->\n\n<!DOCTYPE html>\n<html>\n<head>\n  <title>My Full-Stack Project</title>\n</head>\n<body>\n  <h1>My Project</h1>\n  <p>Start planning your full-stack application here.</p>\n  \n  <!-- Project Plan:\n  1. What will you build?\n  2. What are the main features?\n  3. What tech stack will you use?\n  4. What's your database schema?\n  5. What API endpoints do you need?\n  -->\n</body>\n</html>"},
    {"day": 29, "title": "CI/CD & Deployment to Vercel", "time": "50 min", "lang": "html", "type": "code",
     "lesson": "# CI/CD & Deployment\n\n## Vercel Deployment\n\nVercel is the easiest way to deploy Next.js apps.\n\n```bash\n# Install Vercel CLI\nnpm i -g vercel\n\n# Deploy\nvercel\n\n# Production deploy\nvercel --prod\n```\n\n## GitHub Actions CI/CD\n\n```yaml\n# .github/workflows/ci.yml\nname: CI\non: [push, pull_request]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 20\n      - run: npm ci\n      - run: npm test\n      - run: npm run build\n```\n\n## Environment Variables\n\n```bash\n# .env.local (never commit this)\nNEXT_PUBLIC_API_URL=https://api.myapp.com\nDATABASE_URL=postgresql://...\nSECRET_KEY=...\n```\n\n## Deployment Checklist\n\n- [ ] Environment variables set\n- [ ] CORS configured for production domain\n- [ ] Database migrated\n- [ ] HTTPS enabled\n- [ ] Error monitoring (Sentry)\n- [ ] Performance monitoring",
     "assignment": "Create a deployment pipeline:\n1. Write a GitHub Actions workflow for CI\n2. Configure Vercel deployment for the frontend\n3. Create environment variable documentation\n4. Write a deployment checklist\n5. Set up a basic health check endpoint",
     "starter": "<!-- Deployment Configuration -->\n<!-- Document your deployment setup -->\n\n<!-- GitHub Actions CI workflow -->\n<!-- vercel.json configuration -->\n<!-- Environment variables list -->\n<!-- Deployment checklist -->\n\n<pre>\n# Deployment Plan\n\n## 1. GitHub Actions\n- Runs on: push to main\n- Steps: install, lint, test, build\n\n## 2. Vercel\n- Framework: Next.js\n- Build command: npm run build\n\n## 3. Environment Variables\n- NEXT_PUBLIC_API_URL=\n- ...\n</pre>"},
    {"day": 30, "title": "Portfolio, Resume & What's Next", "time": "45 min", "lang": "html", "type": "code",
     "lesson": "# Day 30: Your Developer Portfolio\n\nCongratulations! You've completed the 30-Day Full-Stack Challenge! 🎉\n\n## What You've Built\n\nOver 30 days, you've learned:\n- **HTML & CSS**: Semantic markup, Flexbox, Grid, responsive design\n- **JavaScript**: ES6+, DOM manipulation, async programming\n- **React**: Components, state, hooks, routing\n- **Backend**: Python, FastAPI, REST APIs\n- **Database**: SQL, SQLAlchemy, authentication\n- **DevOps**: Docker, CI/CD, deployment\n\n## Your Portfolio\n\nYour NOVA LABS portfolio page showcases:\n- Your 4 project submissions with live links\n- Skills validated through the challenge\n- Certificates earned\n- GitHub contribution graph\n\n## Next Steps\n\n1. **Keep building** — The best way to learn is to build real projects\n2. **Contribute to open source** — Find projects on GitHub\n3. **Network** — Share your portfolio on LinkedIn\n4. **Apply** — Your portfolio proves you can build. Start applying!\n5. **Teach others** — Teaching reinforces learning\n\n## Resources\n\n- MDN Web Docs: [developer.mozilla.org](https://developer.mozilla.org)\n- React Docs: [react.dev](https://react.dev)\n- FastAPI Docs: [fastapi.tiangolo.com](https://fastapi.tiangolo.com)",
     "assignment": "Create your developer portfolio page:\n1. A hero section with your name and title\n2. An 'About Me' section\n3. A 'Projects' section showcasing your 4 challenge projects\n4. A 'Skills' section organized by category\n5. A 'Contact' section with links\n6. Make it responsive and visually polished",
     "starter": '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>My Portfolio</title>\n  <style>\n    :root {\n      --primary: #2F67C7;\n      --text: #1B237A;\n    }\n    * { box-sizing: border-box; margin: 0; padding: 0; }\n    body { font-family: sans-serif; color: var(--text); }\n  </style>\n</head>\n<body>\n  <!-- Build your portfolio -->\n  <header>\n    <h1>Your Name</h1>\n    <p>Full-Stack Developer</p>\n  </header>\n</body>\n</html>'},
]

# MCQ templates per phase
def make_mcqs(day_num, phase_idx):
    """Generate 10 MCQs for a given day based on its phase."""
    mcq_banks = {
        0: [  # HTML & CSS
            ("What does HTML stand for?", ["HyperText Markup Language", "High Tech Modern Language", "HyperTransfer Markup Language", "Home Tool Markup Language"], 0, "HTML stands for HyperText Markup Language."),
            ("Which tag is used for the largest heading?", ["<h6>", "<heading>", "<h1>", "<head>"], 2, "The <h1> tag defines the largest heading."),
            ("What is the correct CSS property to change text color?", ["text-color", "font-color", "color", "foreground-color"], 2, "The 'color' property sets the text color in CSS."),
            ("Which CSS property is used to add space inside an element?", ["margin", "padding", "border", "spacing"], 1, "Padding adds space inside an element, between content and border."),
            ("What does the 'display: flex' property do?", ["Makes element invisible", "Creates a flex container", "Adds flexibility to fonts", "Floats the element"], 1, "display: flex creates a flex container for flexible layouts."),
            ("Which HTML tag is semantic for navigation?", ["<div>", "<nav>", "<menu>", "<links>"], 1, "The <nav> tag is the semantic element for navigation sections."),
            ("How do you make a CSS comment?", ["// comment", "/* comment */", "<!-- comment -->", "# comment"], 1, "CSS comments use /* */ syntax."),
            ("Which property creates rounded corners?", ["corner-radius", "border-radius", "round-corner", "border-round"], 1, "border-radius creates rounded corners in CSS."),
            ("What does 'responsive design' mean?", ["Fast loading", "Adapts to different screen sizes", "Uses animations", "Server-side rendering"], 1, "Responsive design means the layout adapts to different screen sizes."),
            ("Which unit is relative to the parent element's font size?", ["px", "em", "vh", "cm"], 1, "The 'em' unit is relative to the parent element's font size."),
        ],
        1: [  # JavaScript
            ("Which keyword declares a constant in JavaScript?", ["var", "let", "const", "constant"], 2, "The 'const' keyword declares a constant that cannot be reassigned."),
            ("What is the result of typeof null?", ["'null'", "'undefined'", "'object'", "'boolean'"], 2, "typeof null returns 'object' — a known JavaScript quirk."),
            ("Which method adds an element to the end of an array?", ["push()", "append()", "add()", "insert()"], 0, "The push() method adds elements to the end of an array."),
            ("What does === check?", ["Value only", "Type only", "Value and type", "Reference only"], 2, "The === operator checks both value AND type (strict equality)."),
            ("Which array method creates a new array with transformed elements?", ["forEach()", "filter()", "map()", "reduce()"], 2, "map() creates a new array by transforming each element."),
            ("What is a closure?", ["A syntax error", "A function with access to its outer scope", "A way to close the browser", "A loop construct"], 1, "A closure is a function that has access to variables from its outer scope."),
            ("How do you handle errors in async/await?", ["if/else", "try/catch", "error/handle", "promise.error()"], 1, "Use try/catch blocks to handle errors in async/await code."),
            ("What does JSON.parse() do?", ["Converts object to string", "Converts string to object", "Validates JSON", "Creates a new object"], 1, "JSON.parse() converts a JSON string into a JavaScript object."),
            ("Which event fires when a form is submitted?", ["click", "change", "submit", "input"], 2, "The 'submit' event fires when a form is submitted."),
            ("What is the DOM?", ["A programming language", "A tree representation of HTML", "A CSS framework", "A database"], 1, "The DOM is a tree-structured representation of the HTML document."),
        ],
        2: [  # React
            ("What is JSX?", ["A new language", "JavaScript XML syntax extension", "A CSS preprocessor", "A testing framework"], 1, "JSX is a syntax extension that lets you write HTML-like code in JavaScript."),
            ("What hook manages state in a function component?", ["useEffect", "useState", "useContext", "useRef"], 1, "useState is the hook for managing state in function components."),
            ("When does useEffect with an empty dependency array run?", ["Every render", "Only on mount", "Never", "On unmount only"], 1, "useEffect with [] runs only once when the component mounts."),
            ("What are props in React?", ["Global variables", "Read-only inputs to components", "Mutable state", "CSS styles"], 1, "Props are read-only inputs passed from parent to child components."),
            ("How do you conditionally render in JSX?", ["if/else inside JSX", "Ternary operator or &&", "switch statement", "for loop"], 1, "Use ternary operators or && for conditional rendering in JSX."),
            ("What is the virtual DOM?", ["The actual browser DOM", "A lightweight copy of the DOM", "A CSS engine", "A testing tool"], 1, "The virtual DOM is a lightweight JavaScript copy of the actual DOM."),
            ("Which hook handles side effects?", ["useState", "useEffect", "useMemo", "useCallback"], 1, "useEffect handles side effects like data fetching and subscriptions."),
            ("What is component composition?", ["Inheriting from a base component", "Building complex UI from smaller components", "Adding CSS to components", "Testing components"], 1, "Composition means building complex UI by combining smaller components."),
            ("What does key prop do in lists?", ["Adds keyboard shortcuts", "Helps React identify which items changed", "Sets access keys", "Encrypts data"], 1, "The key prop helps React efficiently update lists by identifying items."),
            ("How do you share state between sibling components?", ["Global variables", "Lift state up to parent", "Use localStorage", "Direct DOM manipulation"], 1, "Lift state up to the nearest common parent component."),
        ],
        3: [  # Backend
            ("What does REST stand for?", ["Real-time Event State Transfer", "Representational State Transfer", "Remote Server Technology", "Request-Send-Transfer"], 1, "REST stands for Representational State Transfer."),
            ("Which HTTP method is used to create a resource?", ["GET", "POST", "PUT", "DELETE"], 1, "POST is typically used to create new resources."),
            ("What status code means 'Not Found'?", ["400", "401", "403", "404"], 3, "HTTP 404 means the requested resource was not found."),
            ("What is middleware?", ["Database software", "Code that runs between request and response", "Frontend framework", "Testing tool"], 1, "Middleware is code that processes requests before they reach the endpoint."),
            ("What does CORS stand for?", ["Cross-Origin Resource Sharing", "Client-Origin Request System", "Cross-Object Response Service", "Cache-Origin Resource System"], 0, "CORS stands for Cross-Origin Resource Sharing."),
            ("Which Python type hint means 'returns nothing'?", ["void", "None", "null", "empty"], 1, "In Python, None is used as the return type hint for functions that return nothing."),
            ("What is Pydantic used for?", ["Database ORM", "Data validation and serialization", "Testing", "Deployment"], 1, "Pydantic is used for data validation and serialization in Python."),
            ("What is dependency injection?", ["Installing packages", "Providing dependencies to functions automatically", "Injecting CSS", "A security vulnerability"], 1, "DI is a pattern where dependencies are provided to functions automatically."),
            ("Which HTTP method is idempotent?", ["POST", "PUT", "PATCH (sometimes)", "All of the above"], 1, "PUT is idempotent — calling it multiple times has the same effect as once."),
            ("What format do REST APIs typically use?", ["XML", "JSON", "CSV", "HTML"], 1, "REST APIs typically use JSON for data exchange."),
        ],
        4: [  # Database & Auth
            ("What does SQL stand for?", ["Structured Query Language", "Simple Query Logic", "Server Query Language", "Structured Question Language"], 0, "SQL stands for Structured Query Language."),
            ("What is an ORM?", ["Object-Relational Mapping", "Online Resource Manager", "Optimized Request Method", "Object Reference Model"], 0, "ORM maps database tables to programming language objects."),
            ("What is a foreign key?", ["A primary key from another country", "A field referencing another table's primary key", "An encrypted key", "A deprecated key"], 1, "A foreign key references the primary key of another table."),
            ("Why should you hash passwords?", ["To make them shorter", "To protect them if the database is compromised", "To validate format", "To encrypt the database"], 1, "Hashing protects passwords even if the database is breached."),
            ("What is JWT?", ["Java Web Token", "JSON Web Token", "JavaScript Worker Thread", "Joint Web Technology"], 1, "JWT stands for JSON Web Token, used for stateless authentication."),
            ("What is RBAC?", ["Remote Backup and Cache", "Role-Based Access Control", "Request-Based API Call", "Runtime Binary Access Check"], 1, "RBAC controls access to resources based on user roles."),
            ("What is an index in a database?", ["A table of contents", "A data structure for faster queries", "A primary key", "A backup copy"], 1, "An index is a data structure that speeds up database queries."),
            ("What is a database migration?", ["Moving to a new server", "Version-controlled schema changes", "Backing up data", "Importing CSV files"], 1, "Migrations are version-controlled changes to the database schema."),
            ("What is bcrypt?", ["A database engine", "A password hashing algorithm", "A JavaScript framework", "A CSS preprocessor"], 1, "bcrypt is a password hashing algorithm designed for security."),
            ("What is the purpose of a refresh token?", ["To refresh the page", "To get a new access token without re-login", "To update the database", "To clear the cache"], 1, "Refresh tokens allow getting new access tokens without re-authenticating."),
        ],
        5: [  # Deployment
            ("What is Docker?", ["A programming language", "A containerization platform", "A web framework", "A database"], 1, "Docker is a platform for building and running containerized applications."),
            ("What is CI/CD?", ["Code Integration/Code Delivery", "Continuous Integration/Continuous Deployment", "Container Integration/Container Delivery", "Client Interface/Client Design"], 1, "CI/CD stands for Continuous Integration and Continuous Deployment."),
            ("What is a Dockerfile?", ["A documentation file", "Instructions to build a Docker image", "A configuration for Docker Compose", "A Docker log file"], 1, "A Dockerfile contains instructions for building a Docker image."),
            ("What does Vercel primarily host?", ["Databases", "Frontend and serverless functions", "Email servers", "Game servers"], 1, "Vercel primarily hosts frontend applications and serverless functions."),
            ("What is an environment variable?", ["A JavaScript variable", "A configuration value set outside the code", "A CSS variable", "A database field"], 1, "Environment variables are configuration values set outside the source code."),
            ("What is a health check endpoint?", ["A medical API", "An endpoint that confirms the service is running", "A security scanner", "A performance test"], 1, "A health check endpoint returns a simple response to confirm the service is up."),
            ("What does 'npm run build' typically do?", ["Starts the dev server", "Creates a production-ready bundle", "Runs tests", "Installs dependencies"], 1, "npm run build creates an optimized production build."),
            ("What is the purpose of .env files?", ["To store environment-specific configuration", "To define CSS styles", "To write documentation", "To configure Git"], 0, ".env files store environment-specific configuration variables."),
            ("What is a reverse proxy?", ["A proxy that blocks requests", "A server that forwards requests to backend services", "A caching mechanism", "A firewall"], 1, "A reverse proxy sits in front of servers and forwards client requests."),
            ("Why use multi-stage Docker builds?", ["To run multiple apps", "To create smaller final images", "To build faster", "To add more features"], 1, "Multi-stage builds produce smaller images by separating build and runtime."),
        ],
    }
    bank = mcq_banks.get(phase_idx, mcq_banks[0])
    return bank[:10]

def main():
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()

    # Clear existing data
    cur.execute("DELETE FROM mcq_questions")
    cur.execute("DELETE FROM days")
    cur.execute("DELETE FROM phases")
    conn.commit()
    print("Cleared existing content.")

    now = datetime.now(timezone.utc).isoformat()

    # Insert phases
    phase_ids = {}
    for i, p in enumerate(PHASES):
        pid = str(uuid.uuid4())
        phase_ids[i] = pid
        cur.execute(
            "INSERT INTO phases (id, name, description, tagline, accent_color, skills_list, display_order, is_published, created_at) VALUES (?,?,?,?,?,?,?,?,?)",
            (pid, p["name"], f"Phase {i+1}: {p['tagline']}", p["tagline"], p["color"], json.dumps(p["skills"]), i+1, 1, now),
        )
    print(f"Inserted {len(PHASES)} phases.")

    # Insert days and MCQs
    for d in DAYS:
        day_num = d["day"]
        phase_idx = (day_num - 1) // 5
        phase_id = phase_ids[phase_idx]
        day_id = str(uuid.uuid4())

        cur.execute(
            """INSERT INTO days (id, phase_id, day_number, title, estimated_time, lesson_content,
            assignment_prompt, assignment_type, starter_code, reference_solution, language,
            is_published, is_draft, version, created_at, updated_at)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
            (day_id, phase_id, day_num, d["title"], d["time"], d["lesson"],
             d["assignment"], d["type"], d["starter"], None, d["lang"],
             1, 0, 1, now, now),
        )

        # Insert MCQs
        mcqs = make_mcqs(day_num, phase_idx)
        for qi, (q, opts, correct, explanation) in enumerate(mcqs):
            cur.execute(
                "INSERT INTO mcq_questions (id, day_id, question_text, options, correct_option_index, explanation, display_order) VALUES (?,?,?,?,?,?,?)",
                (str(uuid.uuid4()), day_id, q, json.dumps(opts), correct, explanation, qi + 1),
            )

        print(f"  Day {day_num}: {d['title']} + {len(mcqs)} MCQs")

    conn.commit()
    conn.close()
    print(f"\nDone! Seeded {len(DAYS)} days with MCQs.")

if __name__ == "__main__":
    main()
