export const PHASES = [
  {
    id: 1,
    name: "HTML, CSS & Foundations",
    days: "1-5",
    color: "#2F67C7",
    skills: ["HTML5", "CSS3", "Responsive Design", "Flexbox", "Grid"],
  },
  {
    id: 2,
    name: "JavaScript & DOM",
    days: "6-10",
    color: "#32D3E6",
    skills: ["ES2022", "DOM Manipulation", "Events", "Async/Await", "Fetch API"],
  },
  {
    id: 3,
    name: "React & State Management",
    days: "11-15",
    color: "#22C7D4",
    skills: ["React 18", "Hooks", "Context API", "React Router", "Component Patterns"],
  },
  {
    id: 4,
    name: "Backend with Python & FastAPI",
    days: "16-20",
    color: "#8A2BBE",
    skills: ["Python", "FastAPI", "REST APIs", "Authentication", "SQLAlchemy"],
  },
  {
    id: 5,
    name: "Database & DevOps",
    days: "21-25",
    color: "#D21D8E",
    skills: ["MongoDB", "PostgreSQL", "Docker", "CI/CD", "Deployment"],
  },
  {
    id: 6,
    name: "Full-Stack Projects",
    days: "26-30",
    color: "#F02B8F",
    skills: ["System Design", "Testing", "Performance", "Portfolio", "Interview Prep"],
  },
];

export const XP_VALUES = {
  quiz_complete: 50,
  quiz_bonus: 30,
  assignment_submit: 80,
  project_accepted: 200,
  project_merit: 100,
  community_post: 15,
  doubt_reply: 20,
  official_answer: 50,
  referral_convert: 100,
  daily_login: 10,
  streak_7: 150,
  streak_14: 300,
  streak_30: 500,
} as const;

export const BADGE_DEFINITIONS = {
  first_login: { name: "First Login", rarity: "common" },
  day1_complete: { name: "Day 1 Complete", rarity: "common" },
  phase1_complete: { name: "Phase 1 Complete", rarity: "common" },
  all_30_days: { name: "30-Day Champion", rarity: "epic" },
  perfect_quiz: { name: "Perfect Quiz", rarity: "common" },
  perfect_week: { name: "Perfect Week", rarity: "rare" },
  merit_project: { name: "Merit Project", rarity: "rare" },
  excellence_project: { name: "Excellence Project", rarity: "epic" },
  week_warrior: { name: "Week Warrior", rarity: "common" },
  fortnight_fighter: { name: "Fortnight Fighter", rarity: "rare" },
  thirty_day_legend: { name: "30-Day Legend", rarity: "legendary" },
  first_post: { name: "First Post", rarity: "common" },
  helpful_human: { name: "Helpful Human", rarity: "rare" },
  community_builder: { name: "Community Builder", rarity: "rare" },
  bug_squasher: { name: "Bug Squasher", rarity: "common" },
  first_deploy: { name: "First Deploy", rarity: "rare" },
  four_deploys: { name: "Four Deploys", rarity: "epic" },
  speed_runner: { name: "Speed Runner", rarity: "rare" },
  early_bird: { name: "Early Bird", rarity: "common" },
  night_owl: { name: "Night Owl", rarity: "common" },
} as const;
